# Use root/example as user/password credentials
version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081

  express:
    build: ./Express
    ports:
      - 3000:3000
    links:
      - mongo
    volumes:
      - express_images:/usr/src/app/images/item_images
    env_file: .env-prod
    environment:
      - FRONTEND_URL=${FRONTEND_URL}

  angular:
    build: ./Angular
    ports: 
      - 4200:4200
    depends_on:
      - express
    volumes:
      - ./Angular/frontend/src:/usr/src/app/src

  portainer:
    image: portainer/portainer
    command: -H unix:///var/run/docker.sock
    restart: always
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

volumes:
  portainer_data:
  express_images:
  mongo_data: